apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-svc
  namespace: kube-system
spec:
  selector:
    k8s-app: nginx-ingress-controller
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 8081