apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0
        imagePullPolicy: Always
        command:
        - /heapster
        - --api-server=true
        - --secure-port=0
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 8082
    name: heapster
  selector:
    k8s-app: heapster
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-heapster
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/enable-ipport: "true"
    ingress.kubernetes.io/ipport: "30007"
spec:
  rules:
  - host: heapster.cloudin.com
    http:
      paths:
      - path: /
        backend:
          serviceName: heapster
          servicePort: 8082