apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-tcp-deploy
  labels:
    ingress: tcp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ingress: tcp
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-tcp-svc
  namespace: default
  labels:
    ingress: tcp
spec:
  selector:
    ingress: tcp
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: tcp