apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  annotations:
    federation.kubernetes.io/replica-set-preferences: |
      {
         "rebalance": true,
         "clusters": {
             "federation193": {
                 "minReplicas": 0,
                 "maxReplicas": 10,
                 "weight": 1
             },
             "federation184": {
                 "minReplicas": 0,
                 "maxReplicas": 10,
                 "weight": 1
             }
         }
      }
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.cloudin.com/cloudin/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80